In [5]:
test = True 
for i in range(10,1,-1):
    print(i)
    if test:
        i+=1
        test = False


10
9
8
7
6
5
4
3
2


In [10]:
a = True and 8 or 3
a

8

In [5]:
a = "apple"

a[-3:]

'ple'

In [7]:
"c" > "b"

True

In [9]:
for i in range(0,3):
    print(i)

0
1
2


In [3]:
import numpy as np
K = [[2,0,1],[0,1,2],[0,0,1]]
K = np.array(K)
Kinv = np.linalg.inv(K)
print(Kinv)

[[ 0.5  0.  -0.5]
 [ 0.   1.  -2. ]
 [ 0.   0.   1. ]]


In [5]:
pts1 = [[1,2],[3,4],[1,1]]
pts1 = np.array(pts1)

print(pts1.T)

[[1 3 1]
 [2 4 1]]


In [1]:
type(1)

int

In [24]:
list = [1,2,3,4,5,6,7,8,9,10]
def binSearch(list,target,left,right):
    i = left+int((right-left)/2)
    if i == 0: return i
    if i > len(list): return len(list)

    leftSmaller = list[i-1] < target
    rightLarger = list[i] >= target 
    if leftSmaller and rightLarger:
        return i
    if not leftSmaller:
        right = i 
    elif not rightLarger:
        left = i+1
    return binSearch(list,target,left,right)

print(binSearch(list,0,0,len(list)))
print("what")


0
what
